### ISSUE TITLE
Warnings generated by `npm install` on Ubuntu Server 22.04.3

### ISSUE THREAD

**Issue by so7ow** [deezy-inc/sat-hunter#56]
Any thoughts on what's going on here?

```
 $ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sat-hunter@1.0.0',
npm WARN EBADENGINE   required: { node: '>=18.x', npm: '9.x' },
npm WARN EBADENGINE   current: { node: 'v21.6.1', npm: '10.2.4' }
npm WARN EBADENGINE }
```

I'm going to ignore and continue. Wish me luck!

**Comment by natureplant-ai** [comment]
Wishing hear good excellent results.
Thank you very much 

เมื่อวันที่ 10 กุมภาพันธ์ ค.ศ. 2024 7 นาฬิกา 46 นาที 43 วินาที GMT+07:00, so7ow ***@***.***> เขียนว่า:

**Comment by so7ow** [comment]
Warnings appear to be irrelevant. Looks to be working.
