### ISSUE TITLE
What does this excluded_tags output mean?

### ISSUE THREAD

**Issue by so7ow** [deezy-inc/sat-hunter#57]
Trying to interpret this output:

```
 excluded_tags: [
    [ 'omega' ],
    [ 'alpha' ],
    [ 'block_78' ],
    [ 'vintage_nakamoto' ],
    [ 'pizza' ],
    [ 'nakamoto' ],
    [ 'taproot_activation' ],
    [ 'nomenome' ],
    [ 'birdshit' ],
    [ 'erin_custom' ]
  ],
```

...does that mean I've excluded those sats in my search? I didn't mean to... I have all the include and exclude lines commented out in the .env file.

**Comment by so7ow** [comment]
I got an uncommon sat segregated and sent out to my rare sat wallet. That was exciting but I'm still not sure things are working correctly. When I do a manual search at, for example, ordiscan I see palindromes and various other sats in the utxo that the auto hunter doesn't seem to be noticing, or at least definitely isn't sending to my wallet. Any thoughts on that? I have all the include_tags and exclude_tags commented out, so my assumption is everything is included then?

**Comment by habibitcoin** [comment]
Hi @so7ow , if the excluded_tags are not defined, we set some reasonable defaults to prevent you getting flooded with unvaluable sats (e.g. omega/alpha)

https://docs.deezy.io/#operation/scanUtxoOrAddress!path=0/excluded_tags&t=request 

To explicitly include all tag types, set EXCLUDE_TAGS="" in your .env

**Comment by so7ow** [comment]
Ah, thanks, I missed that in the documentation. I'll give it a try!

Not sure how to show you an example UTXO since by the time it's scanned by the script, it's deposited back to the exchange.

**Comment by habibitcoin** [comment]
Keep us posted, dont hesitate to reach back out! Going to close this for now
